version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
before_build:
- cmd:  >-
    dotnet tool install --tool-path . nbgv

    nbgv cloud

    nuget restore
build:
  project: AssemblyInfoGenerationSdk.sln
  publish_nuget: true
  verbosity: minimal
